package com.dpworld.fms.domain;
import java.time.*; import java.util.*;
public final class FleetJob {
  private final UUID id; private final String number; private final JobType type; private final int priority; private final String source; private final String destination; private final Set<String> requiredCapabilities; private final Instant requestedStart; private final Instant deadline; private JobStatus status; private UUID assignedAsset; private final List<JobEvent> events=new ArrayList<>();
  public FleetJob(UUID id,String number,JobType type,int priority,String source,String destination,Set<String> requiredCapabilities,Instant requestedStart,Instant deadline,String actor){ this.id=Objects.requireNonNull(id);this.number=Objects.requireNonNull(number);this.type=Objects.requireNonNull(type);this.priority=priority;this.source=source;this.destination=destination;this.requiredCapabilities=Set.copyOf(requiredCapabilities==null?Set.of():requiredCapabilities);this.requestedStart=requestedStart;this.deadline=deadline;this.status=JobStatus.CREATED; events.add(new JobEvent(UUID.randomUUID(),id,null,status,Instant.now(),actor,"job created")); }
  public synchronized void transition(JobStatus target,String actor,String reason){ if(!status.canTransitionTo(target)) throw new IllegalStateException("Invalid job transition: "+status+" -> "+target); var old=status;status=target;events.add(new JobEvent(UUID.randomUUID(),id,old,target,Instant.now(),actor,reason)); }
  public synchronized void assign(UUID assetId,String actor){ if(status!=JobStatus.SCHEDULED) throw new IllegalStateException("job must be scheduled"); assignedAsset=assetId;transition(JobStatus.ASSIGNED,actor,"asset assigned"); }
  public UUID id(){return id;} public String number(){return number;} public JobType type(){return type;} public int priority(){return priority;} public String source(){return source;} public String destination(){return destination;} public Set<String> requiredCapabilities(){return requiredCapabilities;} public Instant requestedStart(){return requestedStart;} public Instant deadline(){return deadline;} public JobStatus status(){return status;} public UUID assignedAsset(){return assignedAsset;} public List<JobEvent> events(){return List.copyOf(events);}
}
