package com.dpworld.fms.domain;
import java.util.*;
public enum JobStatus {
  CREATED, VALIDATED, SCHEDULED, ASSIGNED, DISPATCHED, ACKNOWLEDGED, IN_PROGRESS, COMPLETED,
  REJECTED, CANCELLED, FAILED, PAUSED, EXPIRED, WAITING_FOR_RESOURCE;
  private static final Map<JobStatus,Set<JobStatus>> NEXT=Map.ofEntries(
    Map.entry(CREATED,Set.of(VALIDATED,REJECTED,CANCELLED)), Map.entry(VALIDATED,Set.of(SCHEDULED,WAITING_FOR_RESOURCE,REJECTED,CANCELLED)),
    Map.entry(SCHEDULED,Set.of(ASSIGNED,WAITING_FOR_RESOURCE,CANCELLED,EXPIRED)), Map.entry(WAITING_FOR_RESOURCE,Set.of(SCHEDULED,CANCELLED,EXPIRED)),
    Map.entry(ASSIGNED,Set.of(DISPATCHED,SCHEDULED,CANCELLED,FAILED)), Map.entry(DISPATCHED,Set.of(ACKNOWLEDGED,FAILED,CANCELLED)),
    Map.entry(ACKNOWLEDGED,Set.of(IN_PROGRESS,FAILED,CANCELLED)), Map.entry(IN_PROGRESS,Set.of(COMPLETED,PAUSED,FAILED,CANCELLED)),
    Map.entry(PAUSED,Set.of(IN_PROGRESS,FAILED,CANCELLED)));
  public boolean canTransitionTo(JobStatus target){ return NEXT.getOrDefault(this,Set.of()).contains(target); }
}
