package com.dpworld.fms.api;

import java.util.List;import java.util.Map;import java.util.UUID;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;
@Service
public class AssignmentTelemetryReconciler{
 private final JdbcTemplate jdbc;private final ChargingAssignmentService charging;public AssignmentTelemetryReconciler(JdbcTemplate jdbc,ChargingAssignmentService charging){this.jdbc=jdbc;this.charging=charging;}
 public void reconcile(UUID assetId,double latitude,double longitude,double energyPercent,String operationalStatus){reconcileParking(assetId,latitude,longitude,operationalStatus);reconcileCharging(assetId,latitude,longitude,energyPercent);}
 private void reconcileParking(UUID asset,double lat,double lon,String operational){List<Map<String,Object>>rows=jdbc.queryForList("SELECT pa.*,s.latitude,s.longitude FROM parking_assignments pa JOIN parking_spaces s ON s.id=pa.parking_space_id WHERE pa.asset_id=? AND pa.status IN ('ASSIGNED','EN_ROUTE','ARRIVED') ORDER BY pa.created_at DESC LIMIT 1",asset);if(rows.isEmpty())return;Map<String,Object>a=rows.getFirst();if(a.get("latitude")==null)return;double distance=AutomaticParkingAssignmentService.haversine(lat,lon,((Number)a.get("latitude")).doubleValue(),((Number)a.get("longitude")).doubleValue());double radius=15;if(distance<=radius&&!"ARRIVED".equals(a.get("status"))){jdbc.update("UPDATE parking_assignments SET status='ARRIVED',arrived_at=now(),version=version+1 WHERE id=?",a.get("id"));jdbc.update("UPDATE parking_spaces SET status='OCCUPIED',reserved=FALSE,reservation_expiry=NULL,version=version+1 WHERE id=?",a.get("parking_space_id"));jdbc.update("UPDATE jobs SET status='ACTIVE',actual_start_at=coalesce(actual_start_at,now()),version=version+1 WHERE id=?",a.get("job_id"));jdbc.update("UPDATE assets SET operational_status='PARKED',availability_status='ASSIGNED',version=version+1 WHERE id=?",asset);}else if("ARRIVED".equals(a.get("status"))&&distance>radius*2&&List.of("WORKING","IDLE").contains(operational)){jdbc.update("UPDATE parking_assignments SET status='COMPLETED',completed_at=now(),version=version+1 WHERE id=?",a.get("id"));jdbc.update("UPDATE parking_spaces SET status='AVAILABLE',current_asset_id=NULL,reservation_expiry=NULL,version=version+1 WHERE id=?",a.get("parking_space_id"));jdbc.update("UPDATE jobs SET status='COMPLETED',completed_at=now(),version=version+1 WHERE id=?",a.get("job_id"));jdbc.update("UPDATE job_assignments SET ended_at=now() WHERE job_id=? AND ended_at IS NULL",a.get("job_id"));jdbc.update("UPDATE assets SET current_job_id=NULL,availability_status='AVAILABLE',version=version+1 WHERE id=?",asset);}}
 private void reconcileCharging(UUID asset,double lat,double lon,double energy){List<Map<String,Object>>rows=jdbc.queryForList("SELECT ca.*,l.latitude,l.longitude FROM charging_assignments ca JOIN service_stations s ON s.id=ca.station_id JOIN locations l ON l.id=s.location_id WHERE ca.asset_id=? AND ca.status IN ('ASSIGNED','EN_ROUTE','ARRIVED','CHARGING') ORDER BY ca.created_at DESC LIMIT 1",asset);if(rows.isEmpty())return;Map<String,Object>a=rows.getFirst();double distance=AutomaticParkingAssignmentService.haversine(lat,lon,((Number)a.get("latitude")).doubleValue(),((Number)a.get("longitude")).doubleValue());if(distance<=15&&List.of("ASSIGNED","EN_ROUTE","ARRIVED").contains(a.get("status"))){jdbc.update("UPDATE charging_assignments SET status='CHARGING',arrived_at=coalesce(arrived_at,now()),charging_started_at=now(),version=version+1 WHERE id=?",a.get("id"));jdbc.update("UPDATE service_bays SET status='OCCUPIED',reservation_expiry=NULL,version=version+1 WHERE id=?",a.get("slot_id"));jdbc.update("UPDATE assets SET operational_status='CHARGING',version=version+1 WHERE id=?",asset);}if(energy>=((Number)a.get("target_battery_percentage")).doubleValue())charging.complete((UUID)a.get("id"),"Target battery percentage reached","AUTOMATION");}
}
