package com.dpworld.fms.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ChargingAssignmentService {
  private static final List<String> ACTIVE=List.of("PROPOSED","QUEUED","ASSIGNED","EN_ROUTE","ARRIVED","CHARGING");
  private final JdbcTemplate jdbc; private final ObjectMapper json;
  public ChargingAssignmentService(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}

  public Preview preview(UUID assetId){Map<String,Object>a=asset(assetId);validate(a);List<Candidate> accepted=new ArrayList<>();List<Rejected> rejected=new ArrayList<>();for(Map<String,Object>s:jdbc.queryForList("""
      SELECT st.*,l.latitude,l.longitude,
       (SELECT count(*) FROM charging_assignments ca WHERE ca.station_id=st.id AND ca.status IN ('ASSIGNED','EN_ROUTE','ARRIVED','CHARGING')) active_count,
       (SELECT count(*) FROM charging_assignments ca WHERE ca.station_id=st.id AND ca.status='QUEUED') queue_count,
       (SELECT count(*) FROM service_bays b WHERE b.station_id=st.id AND b.active AND b.status='AVAILABLE') available_slots
      FROM service_stations st JOIN locations l ON l.id=st.location_id WHERE st.station_type='CHARGING' ORDER BY st.priority,st.code
      """)){List<String> reasons=reject(a,s);double distance=distance(a,s);double max=parameter("maximumChargingDistanceMeters",5000);if(distance>max)reasons.add("OUTSIDE_MAXIMUM_DISTANCE");long active=((Number)s.get("active_count")).longValue(),queue=((Number)s.get("queue_count")).longValue(),capacity=((Number)s.get("simultaneous_capacity")).longValue(),queueMax=((Number)s.get("maximum_queue_size")).longValue();boolean immediate=active<capacity&&((Number)s.get("available_slots")).longValue()>0;if(!immediate&&queue>=queueMax)reasons.add("STATION_AND_QUEUE_FULL");if(!reasons.isEmpty()){rejected.add(new Rejected((UUID)s.get("id"),String.valueOf(s.get("code")),reasons));continue;}double utilization=(double)active/capacity,score=distance/Math.max(1,max)+queue/Math.max(1d,queueMax)+utilization-(((Number)a.get("energy_percent")).doubleValue()<=((Number)s.get("critical_battery_threshold")).doubleValue()?1:0)-((Number)s.get("priority")).doubleValue()/1000d;accepted.add(new Candidate((UUID)s.get("id"),String.valueOf(s.get("code")),distance,active,capacity,queue,queueMax,immediate,score,Map.of("distanceMeters",distance,"utilization",utilization,"queueLength",queue)));}accepted.sort(Comparator.comparingDouble(Candidate::score));if(accepted.isEmpty())throw failure(assetId,"NO_COMPATIBLE_CHARGING_CAPACITY",rejected);return new Preview(assetId,accepted.getFirst(),accepted.stream().skip(1).toList(),rejected,parameterVersion());}

  @Transactional public Map<String,Object> assign(UUID assetId,String mode,String reason,String overrideReason,String idempotency,String actor,String correlation){if(idempotency!=null){List<Map<String,Object>>found=jdbc.queryForList("SELECT * FROM charging_assignments WHERE idempotency_key=?",idempotency);if(!found.isEmpty())return found.getFirst();}Preview preview=preview(assetId);Candidate selected=preview.selected();jdbc.queryForMap("SELECT id FROM service_stations WHERE id=? FOR UPDATE",selected.stationId());Map<String,Object>station=jdbc.queryForMap("SELECT * FROM service_stations WHERE id=?",selected.stationId());long active=jdbc.queryForObject("SELECT count(*) FROM charging_assignments WHERE station_id=? AND status IN ('ASSIGNED','EN_ROUTE','ARRIVED','CHARGING')",Long.class,selected.stationId());long queued=jdbc.queryForObject("SELECT count(*) FROM charging_assignments WHERE station_id=? AND status='QUEUED'",Long.class,selected.stationId());int capacity=((Number)station.get("simultaneous_capacity")).intValue(),maxQueue=((Number)station.get("maximum_queue_size")).intValue();UUID slotId=null;String status;if(active<capacity){List<Map<String,Object>>slots=jdbc.queryForList("SELECT id FROM service_bays WHERE station_id=? AND active AND status='AVAILABLE' ORDER BY code FOR UPDATE SKIP LOCKED LIMIT 1",selected.stationId());if(!slots.isEmpty()){slotId=(UUID)slots.getFirst().get("id");jdbc.update("UPDATE service_bays SET status='RESERVED',current_asset_id=?,reservation_expiry=now()+interval '15 minutes',version=version+1 WHERE id=? AND status='AVAILABLE'",assetId,slotId);status="ASSIGNED";}else status=null;}else status=null;if(status==null){if(queued>=maxQueue)throw new IllegalStateException("Charging queue full");status="QUEUED";}UUID id=UUID.randomUUID();double battery=((Number)asset(assetId).get("energy_percent")).doubleValue(),target=((Number)station.get("target_battery_percentage")).doubleValue();Integer queuePosition="QUEUED".equals(status)?Math.toIntExact(queued+1):null;UUID jobId="ASSIGNED".equals(status)?createJob(assetId,selected.stationId(),slotId,selected.score(),actor):null;jdbc.update("""
      INSERT INTO charging_assignments(id,asset_id,station_id,slot_id,job_id,status,assignment_mode,queue_position,battery_at_assignment,
       target_battery_percentage,priority,score,score_breakdown,rejected_candidates,reason,assigned_at,expires_at,created_by,override_reason,parameter_version,correlation_id,idempotency_key)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?::jsonb,?::jsonb,?,CASE WHEN ?='ASSIGNED' THEN now() END,now()+interval '15 minutes',?,?,?,?,?,?)
      """,id,assetId,selected.stationId(),slotId,jobId,status,mode,queuePosition,battery,target,battery<=10?100:80,selected.score(),write(selected.scoreBreakdown()),write(preview.rejected()),reason,status,actor,overrideReason,preview.parameterVersion(),correlation,idempotency);jdbc.update("UPDATE assets SET current_job_id=?,availability_status='RESERVED',version=version+1 WHERE id=?",jobId,assetId);audit(actor,"CHARGING_ASSIGNMENT_CREATED",id,correlation,Map.of("stationId",selected.stationId(),"slotId",slotId==null?"QUEUED":slotId,"status",status,"reason",reason));return jdbc.queryForMap("SELECT * FROM charging_assignments WHERE id=?",id);}

  @Transactional public void complete(UUID id,String reason,String actor){Map<String,Object>a=jdbc.queryForMap("SELECT * FROM charging_assignments WHERE id=? FOR UPDATE",id);if(!ACTIVE.contains(String.valueOf(a.get("status"))))throw new IllegalStateException("charging assignment is already terminal");jdbc.update("UPDATE charging_assignments SET status='COMPLETED',completed_at=now(),reason=?,version=version+1 WHERE id=?",reason,id);if(a.get("slot_id")!=null)jdbc.update("UPDATE service_bays SET status='AVAILABLE',current_asset_id=NULL,reservation_expiry=NULL,version=version+1 WHERE id=?",a.get("slot_id"));if(a.get("job_id")!=null){jdbc.update("UPDATE jobs SET status='COMPLETED',completed_at=now(),version=version+1 WHERE id=?",a.get("job_id"));jdbc.update("UPDATE job_assignments SET ended_at=now() WHERE job_id=? AND ended_at IS NULL",a.get("job_id"));}jdbc.update("UPDATE assets SET current_job_id=NULL,availability_status='AVAILABLE',version=version+1 WHERE id=? AND (current_job_id=? OR current_job_id IS NULL)",a.get("asset_id"),a.get("job_id"));audit(actor,"CHARGING_COMPLETED",id,null,Map.of("reason",reason));promote((UUID)a.get("station_id"),actor);}

  private void promote(UUID stationId,String actor){List<Map<String,Object>>queued=jdbc.queryForList("SELECT * FROM charging_assignments WHERE station_id=? AND status='QUEUED' ORDER BY priority DESC,queue_position,created_at FOR UPDATE SKIP LOCKED LIMIT 1",stationId);List<Map<String,Object>>slots=jdbc.queryForList("SELECT id FROM service_bays WHERE station_id=? AND active AND status='AVAILABLE' ORDER BY code FOR UPDATE SKIP LOCKED LIMIT 1",stationId);if(queued.isEmpty()||slots.isEmpty())return;Map<String,Object>q=queued.getFirst();UUID slot=(UUID)slots.getFirst().get("id"),asset=(UUID)q.get("asset_id");jdbc.update("UPDATE service_bays SET status='RESERVED',current_asset_id=?,reservation_expiry=now()+interval '15 minutes',version=version+1 WHERE id=?",asset,slot);UUID job=createJob(asset,stationId,slot,((Number)q.get("score")).doubleValue(),actor);jdbc.update("UPDATE charging_assignments SET status='ASSIGNED',slot_id=?,job_id=?,queue_position=NULL,assigned_at=now(),version=version+1 WHERE id=?",slot,job,q.get("id"));jdbc.update("UPDATE charging_assignments SET queue_position=queue_position-1 WHERE station_id=? AND status='QUEUED' AND queue_position> ?",stationId,q.get("queue_position"));jdbc.update("UPDATE assets SET current_job_id=?,availability_status='RESERVED',version=version+1 WHERE id=?",job,asset);}
  private UUID createJob(UUID asset,UUID station,UUID slot,double score,String actor){UUID job=UUID.randomUUID();jdbc.update("INSERT INTO jobs(id,job_number,job_type,priority,plant_id,destination_location_id,required_capabilities,status,assigned_asset_id,requested_start_at,created_by) SELECT ?,?,'CHARGING',80,a.plant_id,s.location_id,'[\"ELECTRIC\"]'::jsonb,'ASSIGNED',a.id,now(),? FROM assets a JOIN service_stations s ON s.id=? WHERE a.id=?",job,"CHARGE-"+job.toString().substring(0,8).toUpperCase(),actor,station,asset);jdbc.update("INSERT INTO job_assignments(id,job_id,asset_id,score,assigned_at) VALUES (?,?,?,?,now())",UUID.randomUUID(),job,asset,score);jdbc.update("INSERT INTO resource_reservations(id,resource_type,resource_id,job_id,expires_at) VALUES (?,'CHARGING_BAY',?,?,now()+interval '15 minutes')",UUID.randomUUID(),slot,job);return job;}
  private Map<String,Object>asset(UUID id){List<Map<String,Object>>r=jdbc.queryForList("SELECT a.*,t.code asset_type FROM assets a JOIN asset_types t ON t.id=a.asset_type_id WHERE a.id=?",id);if(r.isEmpty())throw new IllegalArgumentException("unknown asset "+id);return r.getFirst();}
  private void validate(Map<String,Object>a){if(!"ELECTRIC".equals(a.get("energy_source")))throw new IllegalStateException("asset is not electric");if(!List.of("IDLE","PARKED").contains(a.get("operational_status")))throw new IllegalStateException("asset cannot safely travel to charging");if(a.get("last_telemetry_at")==null||((Timestamp)a.get("last_telemetry_at")).toInstant().isBefore(Instant.now().minusSeconds((long)parameter("staleTelemetryThresholdSeconds",60))))throw new IllegalStateException("asset telemetry is stale");if(a.get("current_job_id")!=null)throw new IllegalStateException("asset has conflicting job");}
  private List<String>reject(Map<String,Object>a,Map<String,Object>s){List<String>r=new ArrayList<>();if(!Boolean.TRUE.equals(s.get("active")))r.add("INACTIVE");if(List.of("OFFLINE","OUT_OF_SERVICE").contains(s.get("status")))r.add("STATION_"+s.get("status"));String types=String.valueOf(s.get("supported_asset_types"));if(!"[]".equals(types)&&!types.contains("\""+a.get("asset_type")+"\""))r.add("INCOMPATIBLE_ASSET_TYPE");LocalTime now=LocalTime.now();if(s.get("operating_start")!=null&&s.get("operating_end")!=null){LocalTime start=time(s.get("operating_start")),end=time(s.get("operating_end"));if(now.isBefore(start)||now.isAfter(end))r.add("OUTSIDE_OPERATING_HOURS");}if(Boolean.TRUE.equals(parameters().get("requireChargingRouteAvailability"))&&(a.get("current_location_id")==null||s.get("routing_node_id")==null))r.add("ROUTE_UNAVAILABLE");return r;}
  private LocalTime time(Object value){return value instanceof LocalTime t?t:value instanceof java.sql.Time t?t.toLocalTime():LocalTime.parse(String.valueOf(value));}
  private double distance(Map<String,Object>a,Map<String,Object>s){if(a.get("latitude")==null||s.get("latitude")==null)return Double.POSITIVE_INFINITY;return AutomaticParkingAssignmentService.haversine(((Number)a.get("latitude")).doubleValue(),((Number)a.get("longitude")).doubleValue(),((Number)s.get("latitude")).doubleValue(),((Number)s.get("longitude")).doubleValue());}
  @SuppressWarnings("unchecked")private Map<String,Object>parameters(){try{Map<String,Object>row=jdbc.queryForMap("SELECT version,parameters::text parameters FROM operational_parameter_versions ORDER BY version DESC LIMIT 1");Map<String,Object>p=json.readValue(String.valueOf(row.get("parameters")),Map.class);p.put("_version",row.get("version"));return p;}catch(Exception e){throw new IllegalStateException("invalid operational parameters",e);}}
  private double parameter(String key,double fallback){Object v=parameters().get(key);return v instanceof Number n?n.doubleValue():fallback;}private long parameterVersion(){return ((Number)parameters().get("_version")).longValue();}private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalStateException("cannot serialize assignment",e);}}
  private IllegalStateException failure(UUID asset,String code,Object context){jdbc.update("INSERT INTO assignment_exceptions(id,assignment_type,asset_id,code,detail,context) VALUES (?,'CHARGING',?,?,?,?::jsonb)",UUID.randomUUID(),asset,code,"No compatible charging station or queue capacity",write(context));return new IllegalStateException("No compatible charging station: "+code);}
  private void audit(String actor,String action,UUID id,String correlation,Object after){jdbc.update("INSERT INTO audit_logs(id,occurred_at,actor,action,resource_type,resource_id,correlation_id,after_value) VALUES (?,now(),?,?,'CHARGING_ASSIGNMENT',?,?,?::jsonb)",UUID.randomUUID(),actor,action,id.toString(),correlation,write(after));}
  public record Candidate(UUID stationId,String stationCode,double distanceMeters,long occupancy,long capacity,long queueLength,long maximumQueueSize,boolean immediateSlot,double score,Map<String,Object>scoreBreakdown){}public record Rejected(UUID stationId,String stationCode,List<String>reasons){}public record Preview(UUID assetId,Candidate selected,List<Candidate>alternatives,List<Rejected>rejected,long parameterVersion){}
}
