package com.dpworld.fms.api;

import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.security.Principal;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/charging")
public class ChargingController{
 private final JdbcTemplate jdbc;private final ChargingAssignmentService service;public ChargingController(JdbcTemplate jdbc,ChargingAssignmentService service){this.jdbc=jdbc;this.service=service;}
 @GetMapping("/stations")@PreAuthorize("hasAuthority('charging.read')")public List<Map<String,Object>>stations(){return jdbc.queryForList("""
  SELECT s.*,l.latitude,l.longitude,count(b.id) slots,count(b.id) FILTER(WHERE b.status='AVAILABLE') available_slots,
   count(b.id) FILTER(WHERE b.status='RESERVED') reserved_slots,count(b.id) FILTER(WHERE b.status='OCCUPIED') occupied_slots,
   (SELECT count(*) FROM charging_assignments a WHERE a.station_id=s.id AND a.status='QUEUED') queue_length,
   (SELECT count(*) FROM charging_assignments a WHERE a.station_id=s.id AND a.status IN ('ASSIGNED','EN_ROUTE','ARRIVED','CHARGING')) active_assignments
  FROM service_stations s JOIN locations l ON l.id=s.location_id LEFT JOIN service_bays b ON b.station_id=s.id WHERE s.station_type='CHARGING' GROUP BY s.id,l.id ORDER BY s.priority,s.code
  """);}
 @PostMapping("/stations")@PreAuthorize("hasAuthority('charging.station.manage')")@org.springframework.transaction.annotation.Transactional public Map<String,Object>create(@Valid@RequestBody StationCreate r,Principal actor){UUID location=UUID.randomUUID(),station=UUID.randomUUID();jdbc.update("INSERT INTO locations(id,code,name,kind,latitude,longitude) VALUES (?,?,?,'CHARGING_STATION',?,?)",location,r.code(),r.name(),r.latitude(),r.longitude());jdbc.update("INSERT INTO service_stations(id,location_id,station_type,status,service_type,code,name,plant_id,active,supported_asset_types,supported_connector_types,simultaneous_capacity,maximum_queue_size,priority,minimum_battery_threshold,critical_battery_threshold,target_battery_percentage) VALUES (?,?,'CHARGING','AVAILABLE','ELECTRIC',?,?,?,TRUE,?::jsonb,?::jsonb,?,?,?,?,?,?)",station,location,r.code(),r.name(),r.plantId(),json(r.assetTypes()),json(r.connectorTypes()),r.capacity(),r.maximumQueueSize(),r.priority(),r.minimumThreshold(),r.criticalThreshold(),r.targetPercentage());for(int index=1;index<=r.capacity();index++)jdbc.update("INSERT INTO service_bays(id,station_id,code,status,connector_type) VALUES (?,?,?,'AVAILABLE',?)",UUID.randomUUID(),station,r.code()+"-"+index,r.connectorTypes().getFirst());audit(actor.getName(),"CHARGING_STATION_CREATED",station,r.reason());return jdbc.queryForMap("SELECT * FROM service_stations WHERE id=?",station);}
 @GetMapping("/stations/{id}/capacity")@PreAuthorize("hasAuthority('charging.read')")public Map<String,Object>capacity(@PathVariable("id")UUID id){return jdbc.queryForMap("SELECT simultaneous_capacity capacity,(SELECT count(*) FROM charging_assignments WHERE station_id=? AND status IN ('ASSIGNED','EN_ROUTE','ARRIVED','CHARGING')) occupancy,maximum_queue_size,(SELECT count(*) FROM charging_assignments WHERE station_id=? AND status='QUEUED') queue_length FROM service_stations WHERE id=?",id,id,id);}
 @GetMapping("/assignments")@PreAuthorize("hasAuthority('charging.read')")public List<Map<String,Object>>assignments(){return jdbc.queryForList("SELECT ca.*,a.fleet_number,s.code station_code,b.code slot_code FROM charging_assignments ca JOIN assets a ON a.id=ca.asset_id JOIN service_stations s ON s.id=ca.station_id LEFT JOIN service_bays b ON b.id=ca.slot_id ORDER BY ca.created_at DESC LIMIT 1000");}
 @GetMapping("/exceptions")@PreAuthorize("hasAuthority('charging.read')")public List<Map<String,Object>>exceptions(){return jdbc.queryForList("SELECT e.*,a.fleet_number FROM assignment_exceptions e LEFT JOIN assets a ON a.id=e.asset_id WHERE assignment_type='CHARGING' ORDER BY created_at DESC LIMIT 500");}
 @PostMapping("/assignments/preview")@PreAuthorize("hasAuthority('charging.assign')")public ChargingAssignmentService.Preview preview(@Valid@RequestBody PreviewRequest r){return service.preview(r.assetId());}
 @PostMapping("/assignments")@PreAuthorize("hasAuthority('charging.assign')")public Map<String,Object>assign(@Valid@RequestBody AssignmentRequest r,Principal actor,@RequestHeader(name="X-Correlation-ID",required=false)String correlation){if("MANUAL".equals(r.mode())&&(r.overrideReason()==null||r.overrideReason().isBlank()))throw new IllegalArgumentException("manual assignment requires overrideReason");return service.assign(r.assetId(),r.mode(),r.reason(),r.overrideReason(),r.idempotencyKey(),actor.getName(),correlation);}
 @PostMapping("/assignments/{id}/complete")@PreAuthorize("hasAuthority('charging.assign')")public void complete(@PathVariable("id")UUID id,@Valid@RequestBody Reason r,Principal actor){service.complete(id,r.reason(),actor.getName());}
 @PatchMapping("/stations/{id}/status")@PreAuthorize("hasAuthority('charging.station.manage')")public void status(@PathVariable("id")UUID id,@Valid@RequestBody Status r,Principal actor){if(!List.of("AVAILABLE","PARTIALLY_OCCUPIED","FULL","OUT_OF_SERVICE","OFFLINE").contains(r.status()))throw new IllegalArgumentException("invalid charging station status");jdbc.update("UPDATE service_stations SET status=?,version=version+1 WHERE id=?",r.status(),id);audit(actor.getName(),"CHARGING_STATION_STATUS",id,r.reason());}
 @PutMapping("/stations/{id}")@PreAuthorize("hasAuthority('charging.station.manage')")public void update(@PathVariable("id")UUID id,@Valid@RequestBody StationUpdate r,Principal actor){long active=jdbc.queryForObject("SELECT count(*) FROM charging_assignments WHERE station_id=? AND status IN ('ASSIGNED','EN_ROUTE','ARRIVED','CHARGING')",Long.class,id);if(r.capacity()<active)throw new IllegalArgumentException("capacity cannot be below active charging assignments");long slots=jdbc.queryForObject("SELECT count(*) FROM service_bays WHERE station_id=? AND active",Long.class,id);if(r.capacity()>slots)throw new IllegalArgumentException("active slot count must be at least station capacity");if(jdbc.update("UPDATE service_stations SET name=?,simultaneous_capacity=?,maximum_queue_size=?,priority=?,minimum_battery_threshold=?,critical_battery_threshold=?,target_battery_percentage=?,version=version+1 WHERE id=? AND version=?",r.name(),r.capacity(),r.maximumQueueSize(),r.priority(),r.minimumThreshold(),r.criticalThreshold(),r.targetPercentage(),id,r.version())!=1)throw new IllegalStateException("charging station version conflict");audit(actor.getName(),"CHARGING_STATION_UPDATED",id,r.reason());}
 private void audit(String actor,String action,UUID id,String reason){jdbc.update("INSERT INTO audit_logs(id,occurred_at,actor,action,resource_type,resource_id,after_value) VALUES (?,now(),?,?,'CHARGING_STATION',?,jsonb_build_object('reason',?))",UUID.randomUUID(),actor,action,id.toString(),reason);}
 private String json(Object value){try{return new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(value);}catch(Exception exception){throw new IllegalArgumentException("invalid station configuration",exception);}}
 public record PreviewRequest(@NotNull UUID assetId){}public record AssignmentRequest(@NotNull UUID assetId,@NotBlank String mode,@NotBlank String reason,String overrideReason,String idempotencyKey){}public record Reason(@NotBlank String reason){}public record Status(@NotBlank String status,@NotBlank String reason){}public record StationUpdate(@NotBlank String name,@Min(1)int capacity,@Min(0)int maximumQueueSize,@Min(0)int priority,@DecimalMin("0")@DecimalMax("100")double minimumThreshold,@DecimalMin("0")@DecimalMax("100")double criticalThreshold,@DecimalMin("0")@DecimalMax("100")double targetPercentage,@Min(0)long version,@NotBlank String reason){public StationUpdate{if(criticalThreshold>minimumThreshold)throw new IllegalArgumentException("critical threshold must not exceed minimum threshold");if(targetPercentage<=minimumThreshold)throw new IllegalArgumentException("target percentage must exceed minimum threshold");}}
 public record StationCreate(@NotBlank String code,@NotBlank String name,@NotNull UUID plantId,@NotNull Double latitude,@NotNull Double longitude,@Min(1)int capacity,@Min(0)int maximumQueueSize,@Min(0)int priority,@NotEmpty List<String>assetTypes,@NotEmpty List<String>connectorTypes,@DecimalMin("0")@DecimalMax("100")double minimumThreshold,@DecimalMin("0")@DecimalMax("100")double criticalThreshold,@DecimalMin("0")@DecimalMax("100")double targetPercentage,@NotBlank String reason){public StationCreate{if(criticalThreshold>minimumThreshold)throw new IllegalArgumentException("critical threshold must not exceed minimum threshold");if(targetPercentage<=minimumThreshold)throw new IllegalArgumentException("target percentage must exceed minimum threshold");}}
}
