package com.dpworld.fms.api;
import com.dpworld.fms.domain.*; import com.dpworld.fms.simulator.SampleFleetFactory; import io.swagger.v3.oas.annotations.Operation; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.MediaType; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.method.annotation.SseEmitter; import java.io.IOException; import java.time.*; import java.util.*; import java.util.concurrent.*;
@RestController @RequestMapping("/api") public class OperationsController {
 private final ConcurrentMap<UUID,Asset> assets=new ConcurrentHashMap<>();private final ConcurrentMap<UUID,FleetJob> jobs=new ConcurrentHashMap<>();private final List<SseEmitter> clients=new CopyOnWriteArrayList<>();
 public OperationsController(){new SampleFleetFactory().create(50).forEach(a->assets.put(a.id(),a));}
 @GetMapping("/assets") @Operation(summary="List current assets",description="Viewport filtering is supported for efficient operational map rendering.") List<Asset> assets(@RequestParam(required=false)Double minLat,@RequestParam(required=false)Double minLon,@RequestParam(required=false)Double maxLat,@RequestParam(required=false)Double maxLon){return assets.values().stream().filter(a->minLat==null||a.position().latitude()>=minLat&&a.position().latitude()<=maxLat&&a.position().longitude()>=minLon&&a.position().longitude()<=maxLon).toList();}
 @GetMapping("/assets/{id}") Asset asset(@PathVariable("id") UUID id){return Optional.ofNullable(assets.get(id)).orElseThrow();}
 @GetMapping("/jobs") List<JobView> jobs(){return jobs.values().stream().map(JobView::of).toList();}
 @PostMapping("/jobs") @PreAuthorize("hasAuthority('order.create')") JobView create(@Valid @RequestBody CreateJob r){var id=UUID.randomUUID();var job=new FleetJob(id,"JOB-%s".formatted(id.toString().substring(0,8).toUpperCase()),r.type(),r.priority(),r.source(),r.destination(),r.requiredCapabilities(),r.requestedStart(),r.deadline(),"api");jobs.put(id,job);publish("job.created",JobView.of(job));return JobView.of(job);}
 @PostMapping("/jobs/{id}/transition") @PreAuthorize("hasAuthority('dispatch.execute')") JobView transition(@PathVariable("id") UUID id,@RequestBody @Valid Transition r){var j=Optional.ofNullable(jobs.get(id)).orElseThrow();j.transition(r.status(),"api",r.reason());publish("job.updated",JobView.of(j));return JobView.of(j);}
 @GetMapping("/dashboard/kpis") Map<String,Object> kpis(){return Map.of("totalAssets",assets.size(),"availableAssets",assets.values().stream().filter(a->a.availability()==Availability.AVAILABLE).count(),"workingAssets",assets.values().stream().filter(a->a.status()==AssetStatus.WORKING).count(),"offlineAssets",assets.values().stream().filter(a->a.status()==AssetStatus.OFFLINE).count(),"lowEnergyAssets",assets.values().stream().filter(a->a.energyPercent()<20).count(),"activeJobs",jobs.values().stream().filter(j->!Set.of(JobStatus.COMPLETED,JobStatus.CANCELLED,JobStatus.FAILED).contains(j.status())).count(),"mqttHealth","UP","rabbitmqHealth","UP");}
 @GetMapping(path="/live",produces=MediaType.TEXT_EVENT_STREAM_VALUE) SseEmitter live(){var e=new SseEmitter(0L);clients.add(e);e.onCompletion(()->clients.remove(e));e.onTimeout(()->clients.remove(e));return e;}
 private void publish(String type,Object value){clients.removeIf(e->{try{e.send(SseEmitter.event().name(type).data(value));return false;}catch(IOException x){e.complete();return true;}});}
 public record CreateJob(@NotNull JobType type,@Min(0)@Max(100)int priority,@NotBlank String source,@NotBlank String destination,Set<String> requiredCapabilities,Instant requestedStart,Instant deadline){} public record Transition(@NotNull JobStatus status,@NotBlank String reason){} public record JobView(UUID id,String number,JobType type,int priority,String source,String destination,JobStatus status,UUID assignedAsset,List<JobEvent> history){static JobView of(FleetJob j){return new JobView(j.id(),j.number(),j.type(),j.priority(),j.source(),j.destination(),j.status(),j.assignedAsset(),j.events());}}
}
