package com.dpworld.fms.api;

import com.fasterxml.jackson.databind.ObjectMapper;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.security.Principal;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/automation/parameters")
public class OperationalParametersController{
 private final JdbcTemplate jdbc;private final ObjectMapper json;public OperationalParametersController(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
 @GetMapping @PreAuthorize("hasAuthority('parameters.read')")public Map<String,Object>current(){return jdbc.queryForMap("SELECT version,parameters::text parameters,reason,created_at,created_by FROM operational_parameter_versions ORDER BY version DESC LIMIT 1");}
 @GetMapping("/history")@PreAuthorize("hasAuthority('parameters.read')")public List<Map<String,Object>>history(){return jdbc.queryForList("SELECT version,reason,created_at,created_by,rolled_back_from FROM operational_parameter_versions ORDER BY version DESC LIMIT 100");}
 @PostMapping("/validate")@PreAuthorize("hasAuthority('parameters.read')")public Validation validate(@RequestBody Map<String,Object>parameters){return new Validation(errors(parameters));}
 @PutMapping @PreAuthorize("hasAuthority('parameters.edit')")@Transactional public Map<String,Object>update(@Valid@RequestBody UpdateRequest request,Principal actor){long current=jdbc.queryForObject("SELECT max(version) FROM operational_parameter_versions",Long.class);if(current!=request.expectedVersion())throw new IllegalStateException("configuration version conflict; reload current parameters");List<String>errors=errors(request.parameters());if(!errors.isEmpty())throw new IllegalArgumentException(String.join("; ",errors));validateReferences(request.parameters());long version=jdbc.queryForObject("INSERT INTO operational_parameter_versions(parameters,reason,created_by) VALUES (?::jsonb,?,?) RETURNING version",Long.class,write(request.parameters()),request.reason(),actor.getName());audit(actor.getName(),"OPERATIONAL_PARAMETERS_UPDATED",String.valueOf(version),request.reason());return current();}
 @PostMapping("/{version}/rollback")@PreAuthorize("hasAuthority('parameters.rollback')")@Transactional public Map<String,Object>rollback(@PathVariable("version")long version,@Valid@RequestBody RollbackRequest request,Principal actor){String parameters=jdbc.queryForObject("SELECT parameters::text FROM operational_parameter_versions WHERE version=?",String.class,version);if(parameters==null)throw new IllegalArgumentException("unknown parameter version "+version);jdbc.update("INSERT INTO operational_parameter_versions(parameters,reason,created_by,rolled_back_from) VALUES (?::jsonb,?,?,?)",parameters,request.reason(),actor.getName(),version);audit(actor.getName(),"OPERATIONAL_PARAMETERS_ROLLED_BACK",String.valueOf(version),request.reason());return current();}
 List<String>errors(Map<String,Object>p){List<String>e=new ArrayList<>();percentage(p,"lowBatteryThresholdPercentage",e);percentage(p,"criticalBatteryThresholdPercentage",e);percentage(p,"defaultTargetBatteryPercentage",e);double low=num(p,"lowBatteryThresholdPercentage",20),critical=num(p,"criticalBatteryThresholdPercentage",10),target=num(p,"defaultTargetBatteryPercentage",80);if(critical>low)e.add("critical battery threshold must be <= low threshold");if(target<=low)e.add("target battery percentage must be > low threshold");positive(p,"parkingAssignmentScanIntervalSeconds",e);positive(p,"parkingReservationTimeoutSeconds",e);positive(p,"chargingAssignmentScanIntervalSeconds",e);positive(p,"chargingReservationTimeoutSeconds",e);if(num(p,"parkingReservationTimeoutSeconds",900)<=num(p,"parkingAssignmentScanIntervalSeconds",30))e.add("parking reservation timeout must exceed scan interval");if(num(p,"chargingReservationTimeoutSeconds",900)<=num(p,"chargingAssignmentScanIntervalSeconds",30))e.add("charging reservation timeout must exceed scan interval");for(String key:List.of("parkingDistanceWeight","nextJobDistanceWeight","parkingCongestionWeight","parkingUtilizationWeight","parkingEnergyWeight","chargingDistanceWeight","chargingQueueWeight","chargingUtilizationWeight","chargingEnergyRiskWeight","criticalBatteryBonus","stationPriorityBonus"))if(num(p,key,0)<0)e.add(key+" cannot be negative");if(sum(p,List.of("parkingDistanceWeight","nextJobDistanceWeight","parkingCongestionWeight","parkingUtilizationWeight","parkingEnergyWeight"))<=0)e.add("at least one parking score weight must be > 0");if(sum(p,List.of("chargingDistanceWeight","chargingQueueWeight","chargingUtilizationWeight","chargingEnergyRiskWeight"))<=0)e.add("at least one charging score weight must be > 0");if(num(p,"maximumConcurrentParkingJobs",1)<1||num(p,"maximumConcurrentChargingJobs",1)<1)e.add("concurrent job limits must be at least 1");if(num(p,"defaultMaximumQueueSize",0)<0)e.add("queue size cannot be negative");return e;}
 private void validateReferences(Map<String,Object>p){Object types=p.get("parkingEligibleAssetTypes");if(types instanceof List<?>list)for(Object type:list)if(jdbc.queryForObject("SELECT count(*) FROM asset_types WHERE code=?",Long.class,type)==0)throw new IllegalArgumentException("unknown parking asset type "+type);Object charging=p.get("chargingEligibleAssetTypes");if(charging instanceof List<?>list)for(Object type:list)if(jdbc.queryForObject("SELECT count(*) FROM asset_types WHERE code=?",Long.class,type)==0)throw new IllegalArgumentException("unknown charging asset type "+type);}
 private void percentage(Map<String,Object>p,String k,List<String>e){double n=num(p,k,0);if(n<0||n>100)e.add(k+" must be between 0 and 100");}private void positive(Map<String,Object>p,String k,List<String>e){if(num(p,k,0)<=0)e.add(k+" must be positive");}private double sum(Map<String,Object>p,List<String>keys){return keys.stream().mapToDouble(k->num(p,k,0)).sum();}private double num(Map<String,Object>p,String k,double d){Object v=p.get(k);return v instanceof Number n?n.doubleValue():d;}private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalArgumentException("parameters are not valid JSON",e);}}private void audit(String actor,String action,String id,String reason){jdbc.update("INSERT INTO audit_logs(id,occurred_at,actor,action,resource_type,resource_id,after_value) VALUES (?,now(),?,?,'OPERATIONAL_PARAMETERS',?,jsonb_build_object('reason',?))",UUID.randomUUID(),actor,action,id,reason);}
 public record Validation(List<String>errors){public boolean valid(){return errors.isEmpty();}}public record UpdateRequest(@Min(1)long expectedVersion,@NotNull Map<String,Object>parameters,@NotBlank String reason){}public record RollbackRequest(@NotBlank String reason){}
}
