package com.dpworld.fms.api;
import com.dpworld.fms.domain.*;import com.dpworld.fms.routing.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;
@Repository public class PostgresRoutingGraphRepository implements RoutingGraphRepository{
 private final JdbcTemplate jdbc;public PostgresRoutingGraphRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public Optional<RoutingGraph>findActiveApproved(){List<Map<String,Object>>rows=jdbc.queryForList("SELECT id,version,status FROM routing_graph_versions WHERE status='ACTIVE' AND approved_at IS NOT NULL ORDER BY activated_at DESC LIMIT 1");return rows.isEmpty()?Optional.empty():Optional.of(load(rows.getFirst(),true));}
 public Optional<RoutingGraph>findById(UUID id){List<Map<String,Object>>rows=jdbc.queryForList("SELECT id,version,status FROM routing_graph_versions WHERE id=?",id);return rows.isEmpty()?Optional.empty():Optional.of(load(rows.getFirst(),false));}
 private RoutingGraph load(Map<String,Object>graph,boolean approvedOnly){UUID id=(UUID)graph.get("id");List<MapNode>nodes=jdbc.query("SELECT id,code,latitude,longitude FROM map_nodes WHERE graph_version_id=? AND (?=FALSE OR approved) ORDER BY code",(rs,n)->new MapNode(rs.getString("code"),new GeoPoint(rs.getDouble("latitude"),rs.getDouble("longitude"))),id,approvedOnly);List<RoadSegment>segments=jdbc.query("SELECT s.id,s.code,f.code from_code,t.code to_code,s.distance_m,s.speed_limit_kph,s.congestion_factor,s.priority_factor,s.blocked,s.restricted,s.restrictions::text FROM road_segments s JOIN map_nodes f ON f.id=s.from_node_id JOIN map_nodes t ON t.id=s.to_node_id WHERE s.graph_version_id=? AND (?=FALSE OR s.approved) ORDER BY s.code",(rs,n)->new RoadSegment(rs.getString("id"),rs.getString("from_code"),rs.getString("to_code"),rs.getDouble("distance_m"),rs.getDouble("speed_limit_kph"),Math.max(1,rs.getDouble("congestion_factor")),Math.max(1,rs.getDouble("priority_factor")),rs.getBoolean("blocked"),rs.getBoolean("restricted"),allowedTypes(rs.getString("restrictions")),0,0,0),id,approvedOnly);return new RoutingGraph(id,((Number)graph.get("version")).longValue(),String.valueOf(graph.get("status")),nodes,segments);}
 private Set<AssetType>allowedTypes(String json){if(json==null||json.isBlank())return Set.of();Set<AssetType>types=new HashSet<>();for(AssetType type:AssetType.values())if(json.contains("\""+type.name()+"\""))types.add(type);return types;}
}
