package com.dpworld.fms.api;
import com.dpworld.fms.domain.*;import com.dpworld.fms.routing.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.security.Principal;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/routing")public class RoutingController{private final JdbcTemplate jdbc;private final RoutingGraphImportService imports;private final ProductionRoutingService routing;private final PlannedRouteRepository routes;private final boolean approvedRequired;public RoutingController(JdbcTemplate jdbc,RoutingGraphImportService imports,ProductionRoutingService routing,PlannedRouteRepository routes,@Value("${dpwfms.routing.require-approved-graph:true}")boolean approvedRequired){this.jdbc=jdbc;this.imports=imports;this.routing=routing;this.routes=routes;this.approvedRequired=approvedRequired;}
 @GetMapping("/graphs")@PreAuthorize("hasAuthority('routing.graph.read')")public List<Map<String,Object>>graphs(){return jdbc.queryForList("SELECT id,version,name,status,source_file,source_checksum,created_at,created_by,reviewed_at,reviewed_by,approved_at,approved_by,activated_at,activated_by,import_report::text import_report FROM routing_graph_versions ORDER BY version DESC");}
 @PostMapping("/graphs/validate")@PreAuthorize("hasAuthority('routing.graph.import')")public Object validate()throws Exception{return imports.validateConfiguredFiles().report();}
 @PostMapping("/graphs/import")@PreAuthorize("hasAuthority('routing.graph.import')")public Map<String,Object>importGraph(Principal actor)throws Exception{return imports.importDraft(actor.getName());}
 @PostMapping("/graphs/{id}/review")@PreAuthorize("hasAuthority('routing.graph.review')")public void review(@PathVariable("id")UUID id,@Valid@RequestBody Reason r,Principal actor){imports.review(id,actor.getName(),r.reason());}
 @PostMapping("/graphs/{id}/approve")@PreAuthorize("hasAuthority('routing.graph.approve')")public void approve(@PathVariable("id")UUID id,@Valid@RequestBody Reason r,Principal actor){imports.approve(id,actor.getName(),r.reason());}
 @PostMapping("/graphs/{id}/activate")@PreAuthorize("hasAuthority('routing.graph.activate')")public void activate(@PathVariable("id")UUID id,@Valid@RequestBody Reason r,Principal actor){imports.activate(id,actor.getName(),r.reason());}
 @PostMapping("/graphs/{id}/preview")@PreAuthorize("hasAuthority('routing.graph.read')")public ProductionRoutingService.Result preview(@PathVariable("id")UUID id,@Valid@RequestBody RouteCommand command){return routing.preview(id,request(command));}
 @PostMapping("/route")@PreAuthorize("hasAuthority('routing.route')")public ProductionRoutingService.Result route(@Valid@RequestBody RouteCommand command){return routing.calculate(new RouteRequest(command.fromNode(),command.toNode(),command.assetType(),new VehicleEnvelope(command.heightMetres(),command.widthMetres(),command.lengthMetres(),command.weightTonnes()),command.availableRangeMetres(),command.priority()),command.jobId());}
 @GetMapping("/routes/{id}")@PreAuthorize("hasAuthority('routing.graph.read')")public PlannedRouteRepository.PlannedRoute route(@PathVariable("id")UUID id){return routes.find(id).orElseThrow(()->new IllegalArgumentException("unknown route "+id));}
 @GetMapping("/assets/{id}/current-route")@PreAuthorize("hasAuthority('routing.graph.read')")public Map<String,Object>assetRoute(@PathVariable("id")UUID id){List<Map<String,Object>>result=jdbc.queryForList("SELECT r.id,r.graph_version,r.total_distance_m,r.estimated_seconds,r.route_geojson::text route_geojson,r.failure_reason FROM assets a JOIN routes r ON r.job_id=a.current_job_id WHERE a.id=? ORDER BY r.created_at DESC LIMIT 1",id);return result.isEmpty()?Map.of("status","UNAVAILABLE","failureReason","NO_PERSISTED_ROUTE"):new LinkedHashMap<>(result.getFirst());}
 @GetMapping("/health")@PreAuthorize("hasAuthority('routing.graph.read')")public Map<String,Object>health(){List<Map<String,Object>>active=jdbc.queryForList("SELECT id,version,status,activated_at FROM routing_graph_versions WHERE status='ACTIVE' AND approved_at IS NOT NULL LIMIT 1");return active.isEmpty()?Map.of("status",approvedRequired?"DOWN":"UNKNOWN","reason","NO_ACTIVE_APPROVED_GRAPH","approvedGraphRequired",approvedRequired):Map.of("status","UP","graph",active.getFirst(),"approvedGraphRequired",approvedRequired);}
 private RouteRequest request(RouteCommand command){return new RouteRequest(command.fromNode(),command.toNode(),command.assetType(),new VehicleEnvelope(command.heightMetres(),command.widthMetres(),command.lengthMetres(),command.weightTonnes()),command.availableRangeMetres(),command.priority());}
 public record Reason(@NotBlank String reason){}public record RouteCommand(@NotBlank String fromNode,@NotBlank String toNode,@NotNull AssetType assetType,@Positive double heightMetres,@Positive double widthMetres,@Positive double lengthMetres,@Positive double weightTonnes,@PositiveOrZero double availableRangeMetres,@Min(0)@Max(100)int priority,UUID jobId){}
}
