package com.dpworld.fms.routing;
import java.util.*;
public final class AStarRoutingEngine implements RoutingEngine {
 private final Map<String,MapNode> nodes; private final Map<String,List<RoadSegment>> outgoing;
 public AStarRoutingEngine(Collection<MapNode> nodes,Collection<RoadSegment> roads){this.nodes=new HashMap<>();nodes.forEach(n->this.nodes.put(n.id(),n));outgoing=new HashMap<>();roads.forEach(r->{if(!this.nodes.containsKey(r.from())||!this.nodes.containsKey(r.to()))throw new IllegalArgumentException("road references unknown node");outgoing.computeIfAbsent(r.from(),x->new ArrayList<>()).add(r);});}
 public Route calculate(RouteRequest req){ var start=require(req.from());var goal=require(req.to()); var open=new PriorityQueue<State>(Comparator.comparingDouble(State::f));var g=new HashMap<String,Double>();var previous=new HashMap<String,RoadSegment>();g.put(start.id(),0d);open.add(new State(start.id(),heuristic(start,goal),0));var closed=new HashSet<String>();
  while(!open.isEmpty()){var current=open.poll();if(!closed.add(current.id()))continue;if(current.id().equals(goal.id()))return build(start,goal,previous,g.get(goal.id()),req.availableRangeMetres());for(var road:outgoing.getOrDefault(current.id(),List.of())){if(!valid(road,req))continue;double candidate=g.get(current.id())+road.travelSeconds();if(candidate<g.getOrDefault(road.to(),Double.POSITIVE_INFINITY)){g.put(road.to(),candidate);previous.put(road.to(),road);open.add(new State(road.to(),candidate+heuristic(require(road.to()),goal),candidate));}}}
  throw new RouteNotFoundException("No valid route from "+req.from()+" to "+req.to()); }
 private boolean valid(RoadSegment r,RouteRequest q){var e=q.envelope();return !r.blocked()&&!r.restricted()&&(r.allowedTypes().isEmpty()||r.allowedTypes().contains(q.assetType()))&&(r.maxHeightM()<=0||e.heightM()<=r.maxHeightM())&&(r.maxWeightTonnes()<=0||e.weightTonnes()<=r.maxWeightTonnes());}
 private Route build(MapNode start,MapNode goal,Map<String,RoadSegment> previous,double seconds,double range){var roads=new ArrayList<RoadSegment>();var at=goal.id();while(!at.equals(start.id())){var r=previous.get(at);if(r==null)throw new RouteNotFoundException("route reconstruction failed");roads.add(r);at=r.from();}Collections.reverse(roads);double distance=roads.stream().mapToDouble(RoadSegment::distanceMetres).sum();if(range>0&&distance>range)throw new RouteNotFoundException("insufficient energy range");var path=new ArrayList<MapNode>();path.add(start);roads.forEach(r->path.add(require(r.to())));return new Route(path,roads,distance,seconds);}
 private double heuristic(MapNode a,MapNode b){return 0d; } private MapNode require(String id){var n=nodes.get(id);if(n==null)throw new IllegalArgumentException("unknown node "+id);return n;} private record State(String id,double f,double g){}
}
